### ISSUE TITLE
Tensorflow 2

### ISSUE THREAD

**Issue by DarthPumpkin** [tiangolo/python-machine-learning-docker#6]
It would be nice to have a Docker image with Tensorflow 2.0.0-rc0

**Comment by tiangolo** [comment]
Hey there! I'm currently not being able to maintain this Docker image, some of the source code might be useful, but you might be better off creating something from scratch for yourself.

Check the note here: https://github.com/tiangolo/python-machine-learning-docker/blob/master/README.md#-warning-currently-not-maintained

Given that, I'll now close this issue. But thanks for the idea! ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue and they piled up through time, but now I'm checking each one in order.
